# dont forget to update hugo.nix.toml as well
baseURL = 'https://example.org/'

[[module.imports]]
path = "github.com/tabler/tabler-icons"
[[module.imports.mounts]]
source = "icons"
target = "assets/icons/"
